site_name: Frank's EECS Journey
site_author: Francis Mbugua
site_description: Documenting my EECS self-learning path.

repo_name: franken-st3in/frank.github.io
repo_url: https://github.com/franken-st3in/frank.github.io/

copyright: Copyright &copy; 2026-present Francis Mbugua

theme:
  name: material
  language: en
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  palette:
    # Light Mode Settings
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark Mode Settings
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/franken-st3in
      name: Check out my GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/frank_3nst3in 
      name: Follow me on Twitter
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/1280449790617976915
      name: Chat with me on Discord
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/Novel_Radish_7082/
      name: Chat with me on Reddit
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/254742704311
      name: Message me on WhatsApp
    - icon: fontawesome/brands/telegram
      link: https://t.me/frnc1s
      name: Message me on Telegram
    - icon: fontawesome/solid/envelope
      link: mailto:frankmbugua002@gmail.com
      name: Send me an email
    - icon: fontawesome/solid/code
      link: https://leetcode.com/u/franken-st3in/
      name: View my LeetCode profile
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/frank3nst3in33/
      name: Follow me on Instagram
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@frank3nst3in33
      name: Follow me on TikTok
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/frank3nst3in33/
      name: Connect with me on Facebook

nav:
  - Home: index.md
  - Courses:
    - MIT 6.100L: 6-100L.md
