site_name: Francis's EECS Journey
site_author: Francis Mbugua
site_description: Documenting my core EECS self-learning path from Kenya.

repo_name: franken-st3in/frank.github.io
repo_url: https://github.com/franken-st3in/frank.github.io/

copyright: Copyright &copy; 2026-present Francis Mbugua

theme:
  name: material
  language: en
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  palette:
    # Light Mode Settings
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark Mode Settings
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/franken-st3in/

nav:
  - Home: index.md
  - Courses:
    - MIT 6.100L: 6-100L.md
